  - name: run swarm node 
    ec2:
      key_name: "{{ key_swarm_name }}"
      group: "{{ sg_swarm_name }}"
      instance_type: "{{ type_swarm_node }}"
      image: "{{ ami_swarm }}"
      wait: yes
      wait_timeout: 500
      instance_tags:
        Name: "{{ cluster_swarm }}-master"
        Project: "{{ cluster_swarm }}"
        Role: "swarm-demo"
      region: "{{ aws_region }}"
      ebs_optimized: "{{ ebs_optimized_swarm }}"
      volumes:
           "{{ volumes[item] }}"
      exact_count: "{{ count_swarm_nodes }}" 
      count_tag:
        Name: "{{ cluster_swarm }}-master"
        Project: "{{ cluster_swarm }}"
        Role: "swarm-demo"
      vpc_subnet_id : "{{ subnet_swarm }}"
      assign_public_ip: yes
      instance_profile_name: "{{ ec2_iam_role }}"
    register: ec2
    with_items: cluster_type 
  - name: print ec2
    debug: var=ec2.results.tagged_instances
  - name: Add new instance to host group
    add_host: hostname={{ item.private_ip }} groups=swarm-master ansible_ssh_private_key_file=/var/lib/jenkins/keys/key_swarm_rsa
    with_items: ec2.results.tagged_instances
  - name: Wait for SSH to come up
    wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
    with_items: ec2.results.tagged_instances
  - name: set fact
    set_fact: var_ec2_swarm_master="{{ ec2 }}"
