  - name: run swarm node 
    ec2:
      key_name: "{{ key_swarm_name }}"
      group: "{{ sg_swarm_name }}"
      instance_type: "{{ type_swarm_node }}"
      image: "{{ ami_swarm }}"
      wait: yes
      wait_timeout: 500
      instance_tags:
        Name: "{{ name_swarm_node }}"
        Cluster: "{{ cluster_swarm }}"
        Role: "swarm-demo"
      region: "{{ aws_region }}"
      ebs_optimized: "{{ ebs_optimized_swarm }}"
      volumes:
           "{{ volumes[item] }}"
      exact_count: "{{ count_swarm_nodes }}" 
      count_tag:
        Name: "{{ name_swarm_node }}"
        Project: "{{ cluster_swarm }}"
        Role: "swarm-demo"
      vpc_subnet_id : "{{ subnet_swarm }}"
      assign_public_ip: yes
      instance_profile_name: "{{ ec2_iam_role }}"
    register: ec2
    with_items: env_type
  - name: print ec2
    debug: var=ec2 
