  - name: yum update 
    yum: name=* state=latest 
  - name: download docker 
    get_url: url=https://get.docker.com dest=/tmp/getdocker.sh mode=0755
  - name: install docker
    shell: /tmp/getdocker.sh 

