  - name: debug consul
    debug: var="{{ hostvars[item] }}"
    with_items: groups['swarm-master']
  - name: set fact consul_ip
    set_fact: consul_ip="{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
    with_items: groups['swarm-master']
  - name:  docker opts 
    template: src=docker.sysconfig dest=/etc/default/docker
  - name: hosts for registry 
    template: src=hosts dest=/etc/hosts
  - name: start docker
    service: name=docker enabled=yes state=restarted
