  - name:  docker opts 
    template: src=docker.sysconfig dest=/etc/default/docker
  - name: hosts for registry 
    copy: src=hosts dest=/etc/hosts
  - name: start docker
    service: name=docker enabled=yes state=restarted
