#- name: codepicnic conf
#  template: src=codepicnic.conf dest=/etc/nginx/sites-enabled/codepicnic.conf
#  notify:
#  - restart nginx 
- name: add ubuntu to main group
  user: name={{ deployment_user }} 
        groups={{ app_user }}
        append=yes
- name: devpad dir 
  file: path="/home/{{ app_user }}/.ssh" state="directory" mode=700 owner="{{ app_user }}"
- name: key 
  copy: src=key_codepicnic_deploy.id_rsa dest="/home/{{ app_user }}/.ssh/id_rsa" owner="{{ app_user }}" mode=600
- name: clone  
  git: repo=git@github.com:CodePicnic/devpad.git clone=yes version="{{ app_branch }}" dest="/home/{{ app_user }}/app" accept_hostkey=True
  become: yes
  become_user: "{{ app_user }}"
  ignore_errors: yes
  vars:
    ansible_ssh_pipelining: true
- name: git config
  git_config: name=user.email value="jenkins@codepicnic.com" 
  become: yes
  become_user: "{{ app_user }}"
- name: git config
  git_config: name=user.name value="Jenkins" 
  become: yes
  become_user: "{{ app_user }}"
- name: permissions
  file: path="/home/{{ app_user }}/app" owner="{{ deployment_user }}" group="{{ app_user }}" recurse=yes mode=775
