- hosts: ansible
  connection: local
  roles:
      - swarm-ec2-ami
- hosts: node-swarm-ami 
  roles:
      - base
      - reboot 
      - aws-monitoring-scripts
      - sysdig
      - docker
      - docker-apparmor
      - newrelic
      - swarm
      - swarm-node
      - create-ami
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

