- hosts: manager 
  roles:
      - docker-swarm 
  remote_user: ec2-user 
  become: yes
  become_user: root
  become_method: sudo

- hosts: consul 
  roles:
      - docker-swarm
      - docker-consul 
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo

- hosts: node 
  roles:
      - docker-swarm 
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo

