- hosts: manager 
  roles:
      - docker
      - swarm
      - swarm-consul
      - swarm-manager
      - swarm-registry
  remote_user: ubuntu 
  become: yes
  become_user: root
  become_method: sudo
- hosts: consul 
  roles:
      - docker
        #- swarm
        #- swarm-consul
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

- hosts: node 
  roles:
      - docker
      - swarm
      - swarm-node 
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

