- hosts: app 
  roles:
      - codepicnic-base
      - base
      - sysdig
      - newrelic
      - ruby22
      - passenger
        #- codepicnic-app
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
