- hosts: consul 
  roles:
      - docker-swarm
      - docker-consul
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo

- hosts: node 
  roles:
      - docker-swarm
      - docker-node 
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
- hosts: manager 
  roles:
      - docker-manager
  remote_user: ec2-user 
  become: yes
  become_user: root
  become_method: sudo

