- hosts: all
  connection: local
  vars:
    aws_profile: codepicnic
    aws_region: us-east-1
    security_groups:
    - 
      id: sg-0671fe7e
  tasks:
  - name: Identify your public IP 
    command: curl -4 ip.opstage.com
    register: remote_ip 
  - name: security group
    command: aws ec2 authorize-security-group-ingress --group-id "{{ item.id }}" --protocol tcp --port 0-65535 --cidr "{{ remote_ip.stdout }}/32" --region "{{ aws_region }}" --profile "{{ aws_profile }}"
    with_items:
    - "{{ security_groups }}"
    ignore_errors: yes
